"""Initial migration

Revision ID: 988415e0cc6e
Revises: 
Create Date: 2024-03-17 19:46:36.150912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988415e0cc6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nume', sa.String(length=50), nullable=True),
    sa.Column('prenume', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('parola', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
