"""Create Destinatie table

Revision ID: bd9a623e4a19
Revises: fcf57b3e5d32
Create Date: 2024-03-18 12:53:00.630701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9a623e4a19'
down_revision = 'fcf57b3e5d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinatie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagine', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinatie', schema=None) as batch_op:
        batch_op.drop_column('imagine')

    # ### end Alembic commands ###
