"""Create Destinatie table

Revision ID: fcf57b3e5d32
Revises: 988415e0cc6e
Create Date: 2024-03-18 12:43:44.421414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf57b3e5d32'
down_revision = '988415e0cc6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinatie',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titlu', sa.String(length=100), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=False),
    sa.Column('locatie', sa.String(length=100), nullable=False),
    sa.Column('pret_per_noapte', sa.Float(), nullable=False),
    sa.Column('numar_locuri', sa.Integer(), nullable=False),
    sa.Column('procent_reducere', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destinatie')
    # ### end Alembic commands ###
